<?php

declare(strict_types=1);

namespace Tests\Http;

use Orchestra\Testbench\Concerns\WithWorkbench;
use PHPUnit\Framework\Attributes\Test;
use Prometheus\CollectorRegistry;
use Prometheus\RegistryInterface;
use Prometheus\Storage\InMemory;
use Tests\TestCase;

final class PrometheusMetricsControllerTest extends TestCase
{
    use WithWorkbench;

    private string $endpoint;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->endpoint = route('prometheus');
    }

    private function assertSuccessfulPrometheusResponse($response): void
    {
        $response->assertStatus(200);
        // Every token in this value is case-insensitive (media type per RFC 9110,
        // charset per RFC 2046), and the charset casing emitted by the framework has
        // changed across versions. NOTE: some Content-Type parameters ARE case-sensitive
        // (multipart "boundary", protobuf "proto=") — if this assertion ever covers one,
        // stop comparing the whole header ignoring case.
        $this->assertEqualsIgnoringCase(
            'text/plain; version=0.0.4; charset=UTF-8',
            $response->headers->get('Content-Type'),
        );
    }

    #[Test]
    public function renders_metrics_from_bound_collector_registry(): void
    {
        # Arrange
        $registry = new CollectorRegistry(new InMemory(), false);

        $namespace = 'namespace';
        $name = 'name';
        $help = 'this is a test gauge';
        $labels = ['label1', 'label2'];

        $gauge = $registry->registerGauge(
            $namespace,
            $name,
            $help,
            $labels,
        );

        $value = 123.0;
        $labelValues = ['value1', 'value2'];
        $gauge->set($value, $labelValues);

        $this->app->bind(RegistryInterface::class, fn() => $registry);

        # Act
        $response = $this->get($this->endpoint);

        # Assert
        $this->assertSuccessfulPrometheusResponse($response);

        $response->assertSeeText("{$namespace}_{$name}");
        $response->assertSeeText("# HELP {$namespace}_{$name} {$help}");
        $response->assertSeeText("# TYPE {$namespace}_{$name} gauge");
        $response->assertSeeText(
            "{$namespace}_{$name}{{$labels[0]}=\"$labelValues[0]\",$labels[1]=\"$labelValues[1]\"} {$value}",
            escape: false
        );
    }

    #[Test]
    public function renders_empty_metrics_when_no_metrics_are_registered(): void
    {
        // Arrange: Don't need to create anything since it's already bound by default in the Service Provider
        // Act: call the /metrics endpoint.
        $response = $this->get($this->endpoint);

        // Assert
        $this->assertSuccessfulPrometheusResponse($response);
        $this->assertEmpty($response->getContent());
    }
}
